# Travis config file to build psycopg packages

sudo: required
dist: trusty
language: generic
os: osx

before_script:
    # Set up files required for upload
    - openssl aes-256-cbc
      -K $encrypted_bd656d6a5753_key -iv $encrypted_bd656d6a5753_iv
      -in id_rsa-initd-upload.enc -out /tmp/id_rsa-initd-upload -d
    - chmod 600 known_hosts /tmp/id_rsa-initd-upload

script: ./scripts/open_tunnel.sh

notifications:
  email: false
